spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: xuanyang
    password: 123456
    url: jdbc:mysql://122.152.218.114/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defualtZone: http://localhost:8761/eureka/
