eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka-register3
server:
  port: 8763